/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.awt.Color;
import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sunny
 */
public class Admin_CustomerSetting_Page extends javax.swing.JFrame {

    int IDuser = 1;
    int checkforuse = 0;
    int wenttopage2 = 0;
    
    int getinforpage = 1;
    public Admin_CustomerSetting_Page() {
        initComponents();
        get_info();
        closecheckerforfle();
    }

     public Admin_CustomerSetting_Page(int ID) {
        initComponents();
        IDuser = ID;
        get_info();
        closecheckerforfle();
        
    }
      public Admin_CustomerSetting_Page(int RoomID, int CID, int COD, int ID, int cID1, int checkforuse1, int change){
       initComponents();
      int checkforuse2 = checkforuse1;
        IDuser = ID;
        wenttopage2 = change;
        getID.setText(String.valueOf(cID1));
         sql = "SELECT * FROM hotel.customer_detial WHERE  customer_detial.Customer_ID = ?;";  
   getinforpage = 9;
   getimfofortable();   
        get_info();
        closecheckerforfle();
  
        if(checkforuse2 == 1){
      setCFCT1();}
       getimfofortable();
      getshowCID.setText(String.valueOf(CID));
      getshowCOD.setText(String.valueOf(COD));
      getshowRoomID.setText(String.valueOf(RoomID));
      
      }
     
     private void setCFCT1(){
   int getID1 = Integer.parseInt(getshowID.getText());
   int getSTID1 = Integer.parseInt(showgetSTID.getText());
   try{     
            Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
        
      String sql1 = "UPDATE customer_stay_detail SET Check_For_Customer = 1 WHERE Customer_stay_Detail_ID=?;";
      PreparedStatement st = con.prepareStatement(sql1);  
       st.setInt(1, getSTID1);
       int h = st.executeUpdate();
     
       
     }
             catch(Exception e){
JOptionPane.showMessageDialog(null, "not connected");
}
    }
     
     private void get_info(){
 
     
     try{

    Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
 
    String sql1 = "SELECT * FROM hotel.admin_account WHERE Admin_ID = ?;";
  PreparedStatement st1 = con.prepareStatement(sql1);
  st1.setInt(1, IDuser);
  
  
   ResultSet st11 = st1.executeQuery();
    while(st11.next()){
        int ID = st11.getInt("Admin_ID");
     String username = st11.getString("Admin_Email");
     String password = st11.getString("Admin_password");
     String usernameF = st11.getString("Admin_FName");
     String usernameL = st11.getString("Admin_LName");
     String welcome = "Welcome " + usernameF +" " + usernameL;
     showName.setText(welcome);
     
    }
   
 }
      catch(Exception e){
JOptionPane.showMessageDialog(null, "UserName or Password is incorrect");
}
     
 }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        showName = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Setting1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        getshowID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showgetFN = new javax.swing.JTextField();
        CheckerFN = new javax.swing.JLabel();
        CheckerLN = new javax.swing.JLabel();
        CheckerEM = new javax.swing.JLabel();
        showgetEM = new javax.swing.JTextField();
        showgetLN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        showgetSTID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        getshowCID = new javax.swing.JTextField();
        getshowCOD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        getshowRoomID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        CheckOutBTN = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        CheckInBTN = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        getID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        getLN = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        getFN = new javax.swing.JTextField();
        getEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hotel Reservation");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer Setting");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        showName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showName.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showName, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(showName)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        Logout.setBackground(new java.awt.Color(255, 204, 204));
        Logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 204, 204));
        Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\logout.png")); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\customer-icon-small.png")); // NOI18N
        jLabel4.setText("Customer Setting");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\newcustomersmall.png")); // NOI18N
        jLabel8.setText("Add new customer");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\newadminicon.png")); // NOI18N
        jLabel5.setText("Create new admin account");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\arrow left.png")); // NOI18N
        jLabel1.setText("Back to Main Page");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        Setting1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Setting1.setForeground(new java.awt.Color(255, 255, 255));
        Setting1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\settingicon.png")); // NOI18N
        Setting1.setText("Account Setting");
        Setting1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Setting1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Setting1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Setting1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(363, 363, 363))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(234, 234, 234))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel4)
                                .addGap(145, 145, 145)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(63, 63, 63)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Setting1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Logout))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(Setting1)
                            .addComponent(Logout))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer_ID", "First name", "Last name", "Email", "Customer stay detail ID", "Check in date", "Check out date", "hotel room type ID", "Check for customer", "Check for customer In num"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomerTableMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerTable);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        getshowID.setEditable(false);
        getshowID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getshowIDActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("First Name");

        showgetFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showgetFNActionPerformed(evt);
            }
        });

        CheckerFN.setText("*");

        CheckerLN.setText("*");

        CheckerEM.setText("*");

        jLabel9.setText("Last Name");

        jLabel10.setText("Email");

        showgetSTID.setEditable(false);

        jLabel11.setText("Stay detail ID");

        jButton3.setText("Save only imfo above");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Check in date");

        getshowCID.setEditable(false);

        getshowCOD.setEditable(false);

        jLabel13.setText("Check out date");

        jLabel14.setText("Room type ID");

        getshowRoomID.setEditable(false);

        jButton2.setText("Change Date and Room");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(CheckOutBTN);
        CheckOutBTN.setText("CheckOut");

        jLabel15.setText("Check ");

        buttonGroup1.add(CheckInBTN);
        CheckInBTN.setText("CheckIn");
        CheckInBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInBTNActionPerformed(evt);
            }
        });

        jButton1.setText("Save only date, room and CheckOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Delete.setText("Delete data");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(CheckOutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(CheckInBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showgetEM)
                    .addComponent(showgetSTID)
                    .addComponent(showgetLN)
                    .addComponent(showgetFN)
                    .addComponent(getshowID)
                    .addComponent(getshowCID)
                    .addComponent(getshowCOD)
                    .addComponent(getshowRoomID)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckerFN)
                    .addComponent(CheckerLN)
                    .addComponent(CheckerEM))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getshowID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showgetFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(CheckerFN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showgetLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(CheckerLN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showgetEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(CheckerEM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showgetSTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete)
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getshowCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getshowCOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getshowRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutBTN)
                    .addComponent(CheckInBTN)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setText("Search by ID");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        getID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getIDActionPerformed(evt);
            }
        });

        jLabel18.setText("ID");

        jLabel20.setText("Last name");

        jLabel19.setText("Fisrt name");

        getEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEmailActionPerformed(evt);
            }
        });

        jLabel17.setText("Email");

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("If some boxese are unknown, leave it empty. When click");

        jLabel21.setText("search, look in the table and Double click on the customer ID");

        jLabel22.setText("and click it one more time on the customer row");

        jLabel23.setText(".");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(getFN, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(getLN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(getID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jButton4)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(getEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(getFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(getLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new Lao_Poet_Hotel_Page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(Color.white);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked

        new Lao_Poet_Hotel_Page().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_LogoutMouseClicked

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        Logout.setForeground(Color.white);
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        Logout.setForeground(Color.black);
    }//GEN-LAST:event_LogoutMouseEntered

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        new Lao_Poet_Hotel_Check_Room(IDuser).setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new Admin_CreatNewAdmin_Page(IDuser).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(Color.white);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    new Admin_CustomerSetting_Page(IDuser).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
jLabel4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
jLabel4.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new Admin_main_page(IDuser).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void Setting1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Setting1MouseClicked
        new Admin_AccountSetting_Page(IDuser).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Setting1MouseClicked

    private void Setting1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Setting1MouseExited
        Setting1.setForeground(Color.WHITE);
    }//GEN-LAST:event_Setting1MouseExited

    private void Setting1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Setting1MouseEntered
        Setting1.setForeground(Color.BLACK);
    }//GEN-LAST:event_Setting1MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int getCID = Integer.parseInt(getshowCID.getText());
    int getCOD = Integer.parseInt(getshowCOD.getText());
    int getRoomID = Integer.parseInt(getshowRoomID.getText());
    int customer_ID = Integer.parseInt(getshowID.getText());
    
    if(checkforuse == 1){
    setCFCT0();
    int checkforuse2 = 1;
     new   Admin_CustomerSetting_page2(getRoomID,getCID,getCOD,IDuser, customer_ID, checkforuse2).setVisible(true);
    this.setVisible(false);
    }else{ 
        int checkforuse2 = 0;
        new   Admin_CustomerSetting_page2(getRoomID,getCID,getCOD,IDuser, customer_ID, checkforuse2).setVisible(true);
    this.setVisible(false);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void setCFCT0(){
   int getID1 = Integer.parseInt(getshowID.getText());
   int getSTID1 = Integer.parseInt(showgetSTID.getText());
   try{     
            Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
        
      String sql1 = "UPDATE customer_stay_detail SET Check_For_Customer = 0 WHERE Customer_stay_Detail_ID=?;";
      PreparedStatement st = con.prepareStatement(sql1);  
       st.setInt(1, getSTID1);
       int h = st.executeUpdate();
     
       
     }
             catch(Exception e){
JOptionPane.showMessageDialog(null, "not connected");
}
    }
    
    
    private void getIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getIDActionPerformed
 String sql;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   String EM = getEmail.getText();
   String FN = getFN.getText();
   String LN = getLN.getText();
   if(EM.equals("") && FN.equals("") && LN.equals("")){
   sql = "SELECT * FROM hotel.customer_detial;";
   getinforpage = 1;
   getimfofortable();
   }
   else if(EM.equals("") && FN.equals("")){
   sql = "SELECT * FROM hotel.customer_detial WHERE customer_detial.Customer_Last_Name = ?;";
    getinforpage = 2;
   getimfofortable();
   
   }
   else if(EM.equals("") && LN.equals("")){
   sql = "SELECT * FROM hotel.customer_detial WHERE customer_detial.Customer_First_Name = ?;";
    getinforpage = 3;
   getimfofortable();
   } 
   else if(LN.equals("") && FN.equals("")){
   sql = "SELECT * FROM hotel.customer_detial WHERE customer_detial.Customer_Email = ?;";
    getinforpage = 4;
   getimfofortable();
   }
     else if(FN.equals("")){
   sql = "SELECT * FROM hotel.customer_detial WHERE customer_detial.Customer_Last_Name = ? AND customer_detial.Customer_Email = ? ;";
   getinforpage = 8;
   getimfofortable();
   }
    else if(LN.equals("")){
   sql = "SELECT * FROM hotel.customer_detial WHERE customer_detial.Customer_First_Name = ? AND customer_detial.Customer_Email = ?;";
    getinforpage = 5;
   getimfofortable();
   }
     else if(EM.equals("")){
   sql = "SELECT * FROM hotel.customer_detial WHERE customer_detial.Customer_First_Name = ? AND customer_detial.Customer_Last_Name = ?;";
   getinforpage = 6;
   getimfofortable();
   }
     else {
   sql = "SELECT * FROM hotel.customer_detial WHERE  customer_detial.Customer_Email = ? AND customer_detial.Customer_First_Name = ? AND customer_detial.Customer_Last_Name = ?;";  
     getinforpage = 7;
   getimfofortable();
     }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
        
     sql = "SELECT * FROM hotel.customer_detial WHERE  customer_detial.Customer_ID = ?;";  
   getinforpage = 9;
   getimfofortable();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        
        
        int row = CustomerTable.getSelectedRow();
       TableModel model = CustomerTable.getModel();
        int value1 = (int) model.getValueAt(row, 0);
        getshowID.setText(String.valueOf(value1));
       String value2 =  (String) model.getValueAt(row, 1);
        showgetFN.setText(value2);
          String value3 =  (String) model.getValueAt(row, 2);
        showgetLN.setText(value3);
       String value4 =  (String) model.getValueAt(row, 3);
        showgetEM.setText(value4);
        String value5 =  (String) model.getValueAt(row, 4);   
        showgetSTID.setText(value5);
        
        
        String value6 =  (String) model.getValueAt(row, 5);   
        getshowCID.setText(value6);
        String value7 =  (String) model.getValueAt(row, 6);   
        getshowCOD.setText(value7);
        String value8 =  (String) model.getValueAt(row, 7);   
        getshowRoomID.setText(value8);
     
         String value9 =  (String) model.getValueAt(row, 9); 
     int value91 = Integer.valueOf(value9);
     
     
     
     if(value91 == 1){
     CheckInBTN.setSelected(true);
     checkforuse = 1;
     }
     else if(value91 == 0){
     CheckOutBTN.setSelected(true);
     checkforuse = 0;
     }
      
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void getEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getEmailActionPerformed

    private void CustomerTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMousePressed
     
            
    }//GEN-LAST:event_CustomerTableMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String getFN1 = showgetFN.getText();
        String getLN1 = showgetLN.getText();
        String getEM1 = showgetEM.getText();
        String getID1 = getshowID.getText();
        if(getID1.equals("")){
        JOptionPane.showMessageDialog(null, "Please select customer on the table by double clicking their ID and click it again one more time on their row");
            
        }
        
        else if(getFN1.equals("")||getLN1.equals("")||getEM1.equals("")){
        JOptionPane.showMessageDialog(null, "Please Filled in all the boxese");
           if(getFN1.equals("")){
        CheckerFN.setVisible(true);
        CheckerFN.setForeground(Color.red);
        CheckerFN.setText("Not Fill");
        }
        else{
        CheckerFN.setVisible(false);
        }
        
           if(getLN1.equals("")){
        CheckerLN.setVisible(true);
        CheckerLN.setForeground(Color.red);
        CheckerLN.setText("Not Fill");
        }
           else{
        CheckerLN.setVisible(false);
        }
           
           if(getEM1.equals("")){
        CheckerEM.setVisible(true);
        CheckerEM.setForeground(Color.red);
        CheckerEM.setText("Not Fill");
        }
           else{
        CheckerEM.setVisible(false);
        }
        }
        else{
        closecheckerforfle();
        saveImfo();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void saveImfo(){
     String getFN1 = showgetFN.getText();
        String getLN1 = showgetLN.getText();
        String getEM1 = showgetEM.getText();
        int getID1 = Integer.parseUnsignedInt(getshowID.getText());
        try{     
            Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
   String sql1 = " UPDATE customer_detial SET Customer_First_Name= ? , Customer_Last_Name = ?  , Customer_Email = ? WHERE Customer_ID= ?;"; 
    PreparedStatement st = con.prepareStatement(sql1); 
        st.setString(1, getFN1);
        st.setString(2, getLN1);
        st.setString(3, getEM1);
        st.setInt(4, getID1);
    
        int h = st.executeUpdate();

    if(h>0){ JOptionPane.showMessageDialog(null, "Updated");}
   
   
     }
     
     catch(Exception e){
JOptionPane.showMessageDialog(null, "not connected");
}
    
    }
    
    private void closecheckerforfle(){
    CheckerFN.setVisible(false);
    CheckerLN.setVisible(false);
    CheckerEM.setVisible(false);
    }
    
    
    private void showgetFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showgetFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showgetFNActionPerformed

    private void getshowIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getshowIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getshowIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        int InCID = Integer.parseInt(getshowCID.getText());
        int roomID = Integer.parseInt(getshowRoomID.getText());
        int InCOD = Integer.parseInt(getshowCOD.getText());
        int stay_ID_Customer = Integer.parseInt(showgetSTID.getText());
        int goforsave = 0;
      if(CheckInBTN.isSelected()){
       try{     
            Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
   String sql3 = "UPDATE customer_stay_detail SET inuse = 1 WHERE Customer_stay_Detail_ID= ?;";
    PreparedStatement st = con.prepareStatement(sql3); 
        st.setInt(1, stay_ID_Customer);
        int h = st.executeUpdate();
   
       String sql1 = "SELECT * FROM customer_stay_detail WHERE Check_For_Customer = 1 AND inuse = 0";
   ResultSet rs1 = myStat.executeQuery(sql1);
   while(rs1.next()){
  
    int    SDID = rs1.getInt("Customer_stay_Detail_ID");
    int    CID = rs1.getInt("Check_In_Date");
    int    COD = rs1.getInt("Check_Out_Date");
   int     RID = rs1.getInt("Hotel_Room_Type_ID");
 
 
        
        if( (InCID <= CID && InCOD >= CID && roomID == RID ) || (InCID <= COD && InCOD >= CID && roomID == RID ) || ( CID <= InCID &&  COD>= InCID&& roomID == RID  ) || ( CID <= InCOD &&  COD>= InCOD&& roomID == RID  )){
goforsave = 1;
JOptionPane.showMessageDialog(null, "SDID =" + SDID);
        }
       
   }
   if(goforsave == 0){
     saveimfodatetime();  }
   else if(goforsave == 1){
       JOptionPane.showMessageDialog(null, "Cannot turn on CheckIn again duel to others has already taken the same date and the same room");
       }
       
       }
        catch(Exception e){
JOptionPane.showMessageDialog(null, "not connected");
}}
      else{saveimfodatetime();}
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CheckInBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckInBTNActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
  String getID1 = getshowID.getText();
      

  
  if(getID1.equals("")){
        JOptionPane.showMessageDialog(null, "Please select customer on the table by double clicking their ID and click it again one more time on their row");
            
        }
  else{
    int deletedata = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this, once delete cannot undo");
    if(deletedata == 0){
         int CID3 = Integer.parseInt(getshowID.getText());
  int CDID3 = Integer.parseInt(showgetSTID.getText());
  
  
    try{     
            Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
   String D1 = "DELETE FROM customer_detial WHERE Customer_ID = ? ;";
   PreparedStatement st = con.prepareStatement(D1); 
   st.setInt(1, CID3);
   int h = st.executeUpdate();
   String D2 = "DELETE FROM customer_stay_detail WHERE Customer_stay_Detail_ID = ? ;";
   PreparedStatement st1 = con.prepareStatement(D2); 
   st1.setInt(1, CDID3);
   int j = st1.executeUpdate();
   
    if(h>0 && j >0){ JOptionPane.showMessageDialog(null, "Deleted");}
clearboxese1();
   JOptionPane.showMessageDialog(null, "Delete");
   }
    catch(Exception e){
JOptionPane.showMessageDialog(null, "not connected");
}}}
   
    }//GEN-LAST:event_DeleteActionPerformed

    private void clearboxese1(){
    getshowID.setText("");
    showgetFN.setText("");
    showgetLN.setText("");
            showgetEM.setText("");
            showgetSTID.setText("");
                    getshowCID.setText("");
                    getshowCOD.setText("");
                            getshowRoomID.setText("");
    }
    
    private void saveimfodatetime(){

     int InCID = Integer.parseInt(getshowCID.getText());
   
        int InCOD = Integer.parseInt(getshowCOD.getText());
        int roomID = Integer.parseInt(getshowRoomID.getText());
        int checkforuse3 = 0;
        if(CheckOutBTN.isSelected()){
        checkforuse3 = 0;
        }
       else if(CheckInBTN.isSelected()){
        checkforuse3 = 1;
        } 
    int stay_ID_Customer = Integer.parseInt(showgetSTID.getText());
    
    try{     
            Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
   String sql1 = " UPDATE customer_stay_detail SET Check_In_Date= ? , Check_Out_Date = ?  , Hotel_Room_Type_ID = ?, Check_For_Customer = ?, inuse = 0 WHERE Customer_stay_Detail_ID= ?;"; 
    PreparedStatement st = con.prepareStatement(sql1); 
        st.setInt(1, InCID);
        st.setInt(2, InCOD);
        st.setInt(3, roomID);
        st.setInt(4, checkforuse3);
         st.setInt(5, stay_ID_Customer);
    
        int h = st.executeUpdate();

    if(h>0){ JOptionPane.showMessageDialog(null, "Updated");}
   
   
     }
     
     catch(Exception e){
JOptionPane.showMessageDialog(null, "not connected");
}
    
    
}
    
    private void getimfofortable(){
         String EM = getEmail.getText();
   String FN = getFN.getText();
   String LN = getLN.getText();
  
        String Checkif = "CheckOut";
     DefaultTableModel tblModel = (DefaultTableModel)CustomerTable.getModel();
        while(tblModel.getRowCount() > 0)
            
{
    tblModel.removeRow(0);
}
        
         try{

    Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
   
   PreparedStatement rs = con.prepareStatement(sql);
   if(getinforpage == 1){
   }
   else if(getinforpage == 2){
   rs.setString(1, LN);
   }
   else if(getinforpage == 3){
   rs.setString(1, FN);
   }
   else if(getinforpage == 4){
   rs.setString(1, EM);
   }
   else if(getinforpage == 8){
   rs.setString(1, LN);
   rs.setString(2, EM);
   }
   else if(getinforpage == 5){
   rs.setString(1, FN);
   rs.setString(2, EM);
   }
     else if(getinforpage == 6){
   rs.setString(1, FN);
   rs.setString(2, LN);
   }
     else if(getinforpage == 7){
   rs.setString(1, EM);
   rs.setString(2, FN);
   rs.setString(3, LN);
   }
     else if(getinforpage == 9){
          int CID1 = Integer.valueOf(getID.getText());
   rs.setInt(1, CID1);
   }
   
   ResultSet rs3 = rs.executeQuery();
   while(rs3.next()){
   int Customer_ID = rs3.getInt("Customer_ID");
   String getFN1 = rs3.getString("Customer_First_Name");
   String getLN1 = rs3.getString("Customer_Last_Name");    
   String getEM = rs3.getString("Customer_Email");
   int getSDID = rs3.getInt("Customer_stay_Detail_ID");   
   String sql2 = "SELECT * FROM hotel.customer_stay_detail WHERE customer_stay_detail.Customer_stay_Detail_ID = ?;";
  
   PreparedStatement rs1 = con.prepareStatement(sql2);
   rs1.setInt(1, getSDID);
   ResultSet rs2 = rs1.executeQuery();  
   
   while(rs2.next()){
   
   String CheckInD = rs2.getString("Check_In_Date");
   String CheckOutD = rs2.getString("Check_Out_Date");    
   String HotelRoomTypeID = rs2.getString("Hotel_Room_Type_ID");
   int CheckForCustomer = rs2.getInt("Check_For_Customer"); 
   
   if(CheckForCustomer == 1){
   Checkif = "Check In";
   }
   else if(CheckForCustomer == 0){
   Checkif = "Check Out";
   }
   
   String Array2[] = { String.valueOf(Customer_ID),getFN1,getLN1,getEM ,String.valueOf(getSDID),CheckInD , CheckOutD, HotelRoomTypeID, Checkif, String.valueOf(CheckForCustomer)} ;
   tblModel.addRow(Array2);
    if(getinforpage == 9){
   
        
        
        getshowID.setText(String.valueOf(Customer_ID));
    
        showgetFN.setText(getFN1);
          
        showgetLN.setText(getLN1);
  
        showgetEM.setText(getEM);
         
        showgetSTID.setText(String.valueOf(getSDID));
         
        getshowCID.setText(CheckInD);
         
        getshowCOD.setText(CheckOutD);
        
        getshowRoomID.setText(HotelRoomTypeID);
       

     
     if(CheckForCustomer == 1){
     CheckInBTN.setSelected(true);
     checkforuse = 1;
     }
     else if(CheckForCustomer == 0){
      CheckOutBTN.setSelected(true);
      checkforuse = 0;
     }
       
       
   }
   
   
   }
   
  
   
   
       
   }
   
  }catch(Exception e){
    JOptionPane.showMessageDialog(null, "not Connected");
}    
        
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_CustomerSetting_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_CustomerSetting_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_CustomerSetting_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_CustomerSetting_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_CustomerSetting_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CheckInBTN;
    private javax.swing.JRadioButton CheckOutBTN;
    private javax.swing.JLabel CheckerEM;
    private javax.swing.JLabel CheckerFN;
    private javax.swing.JLabel CheckerLN;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Setting1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField getEmail;
    private javax.swing.JTextField getFN;
    private javax.swing.JTextField getID;
    private javax.swing.JTextField getLN;
    private javax.swing.JTextField getshowCID;
    private javax.swing.JTextField getshowCOD;
    private javax.swing.JTextField getshowID;
    private javax.swing.JTextField getshowRoomID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel showName;
    private javax.swing.JTextField showgetEM;
    private javax.swing.JTextField showgetFN;
    private javax.swing.JTextField showgetLN;
    private javax.swing.JTextField showgetSTID;
    // End of variables declaration//GEN-END:variables
}
