/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.awt.Color;
import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author sunny
 */
public class Admin_AccountSetting_Page extends javax.swing.JFrame {

    int IDuser = 1;
    String EmailfromID;
    String PhonefromID;
    String getpassword;
    public Admin_AccountSetting_Page() {
        initComponents();
        get_info();
          closechecker();
    }

     public Admin_AccountSetting_Page(int ID) {
        initComponents();
        IDuser = ID;
        get_info();
        
        closechecker();
    }
     
     
     
     
     private void closechecker(){
     jLabel14.setVisible(false);
     jLabel15.setVisible(false);
     jLabel19.setVisible(false);
     jLabel20.setVisible(false);
      jLabel16.setVisible(false);
      PSChecker.setVisible(false);
      RPPSChecker.setVisible(false);
      
     }
     
     private void get_info(){
 
     
     try{

    Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
 
    String sql = "SELECT * FROM hotel.admin_account WHERE Admin_ID = ?;";
  PreparedStatement st1 = con.prepareStatement(sql);
  st1.setInt(1, IDuser);
  
  
   ResultSet st11 = st1.executeQuery();
    while(st11.next()){
        int ID = st11.getInt("Admin_ID");
     String username = st11.getString("Admin_Email");
     String password = st11.getString("Admin_password");
     String usernameF = st11.getString("Admin_FName");
     String usernameL = st11.getString("Admin_LName");
     String PN = st11.getString("Admin_PhoneNum");
     String welcome = "Welcome " + usernameF +" " + usernameL;
     showName.setText(welcome);
     FNshow.setText(usernameF);
     LNshow.setText(usernameL);
     EMshow.setText(username);
     PNshow.setText(PN);
     EmailfromID = username;
     PhonefromID = PN;
     getpassword = password;
     
    }
    
 
   
 }
      catch(Exception e){
JOptionPane.showMessageDialog(null, "UserName or Password is incorrect");
}
     
 }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        showName = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Setting = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FNshow = new javax.swing.JTextField();
        LNshow = new javax.swing.JTextField();
        EMshow = new javax.swing.JTextField();
        PNshow = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        GetPS = new javax.swing.JPasswordField();
        OldPSshow = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        GetRPPS = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PSChecker = new javax.swing.JLabel();
        RPPSChecker = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hotel Reservation");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Account Setting");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        showName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showName.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showName, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(showName)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        Logout.setBackground(new java.awt.Color(255, 204, 204));
        Logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 204, 204));
        Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\logout.png")); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
        });

        Setting.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Setting.setForeground(new java.awt.Color(255, 255, 255));
        Setting.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\settingicon.png")); // NOI18N
        Setting.setText("Account Setting");
        Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingMouseEntered(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\newcustomersmall.png")); // NOI18N
        jLabel8.setText("Add new customer");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\arrow left.png")); // NOI18N
        jLabel1.setText("Back to Main Page");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\newadminicon.png")); // NOI18N
        jLabel5.setText("Create new admin account");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sunny\\Desktop\\Hotel\\customer-icon-small.png")); // NOI18N
        jLabel4.setText("Customer Setting");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Setting, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Logout))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(Logout)
                            .addComponent(Setting)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EMshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMshowActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Only update info above");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        GetPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GetPSKeyReleased(evt);
            }
        });

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel9.setText("Email");

        jLabel10.setText("Phone Number");

        jLabel11.setText("Current Password");

        jLabel12.setText("New Password");

        jToggleButton2.setText("Only update password");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        GetRPPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GetRPPSKeyReleased(evt);
            }
        });

        jLabel13.setText("Repeat New Password");

        jLabel14.setText("*");

        jLabel15.setText("*");

        jLabel16.setText("*");

        PSChecker.setText("*");

        RPPSChecker.setText("*");

        jLabel19.setText("*");

        jLabel20.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PNshow, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FNshow)
                    .addComponent(LNshow)
                    .addComponent(EMshow)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OldPSshow)
                    .addComponent(GetPS)
                    .addComponent(GetRPPS, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PSChecker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RPPSChecker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(10, 10, 10)
                .addComponent(jToggleButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OldPSshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(PSChecker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetRPPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(RPPSChecker))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new Lao_Poet_Hotel_Page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(Color.white);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked

        new Lao_Poet_Hotel_Page().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_LogoutMouseClicked

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        Logout.setForeground(Color.white);
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        Logout.setForeground(Color.black);
    }//GEN-LAST:event_LogoutMouseEntered

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        new Lao_Poet_Hotel_Check_Room(IDuser).setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new Admin_CreatNewAdmin_Page(IDuser).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(Color.white);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Admin_CustomerSetting_Page(IDuser).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new Admin_main_page(IDuser).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
      jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
      jLabel1.setForeground(Color.BLACK); 
    }//GEN-LAST:event_jLabel1MouseExited

    private void SettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseClicked
      new Admin_AccountSetting_Page(IDuser).setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_SettingMouseClicked

    private void SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseEntered
      Setting.setForeground(Color.BLACK);
    }//GEN-LAST:event_SettingMouseEntered

    private void SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseExited
       Setting.setForeground(Color.WHITE);
    }//GEN-LAST:event_SettingMouseExited

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
      
        String FN =FNshow.getText();
        String LN = LNshow.getText();
        String EM = EMshow.getText();
        String PN = PNshow.getText();
        
       String CHECKEMrepeat ;
       String CHECKPNrepeat ;
       int checkEMR = 0;
       int checkPhoneR = 0;
       int EmailID = 0;
       int PhoneID = 0;
        try{     
            Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
   
   String sql = "SELECT * FROM hotel.admin_account;"; 
   PreparedStatement st = con.prepareStatement(sql); 
   ResultSet st1 = st.executeQuery();
     while(st1.next()){
         CHECKEMrepeat = st1.getString("Admin_Email");
         CHECKPNrepeat = st1.getString("Admin_PhoneNum");
      if(EM.equals(EmailfromID)){
          EmailID= 1;
      }
          if(CHECKEMrepeat.equals(EM)){
         checkEMR = 1;
         }
         if(PhonefromID.equals(PN)){
         PhoneID = 1;
         }
         if(CHECKPNrepeat.equals(PN)){
         checkPhoneR = 1;
         }       
   }
       if(FN.equals("") || LN.equals("") || EM.equals("") || PN.equals("")){
       JOptionPane.showMessageDialog(null, "Please enter all the boxese");
       if(FN.equals("")){
       jLabel19.setVisible(true);
       jLabel19.setForeground(Color.red);
       jLabel19.setText("First name not fill");
       }
       else{
         jLabel19.setVisible(false);
       }
       
         if(LN.equals("")){
       jLabel20.setVisible(true);
       jLabel20.setForeground(Color.red);
       jLabel20.setText("Last name not fill");
       }
       else{
         jLabel20.setVisible(false);
       }
         
            if(EM.equals("")){
       jLabel14.setVisible(true);
       jLabel14.setForeground(Color.red);
       jLabel14.setText("Email not fill");
       }
       else{
         jLabel14.setVisible(false);
       }
       
                 if(PN.equals("")){
       jLabel15.setVisible(true);
       jLabel15.setForeground(Color.red);
       jLabel15.setText("Phone number not fill");
       }
       else{
         jLabel15.setVisible(false);
       }
            
       }
    else{
         
         if((EmailID == 1 && PhoneID == 1) || (EmailID == 1 && checkPhoneR == 0) || (PhoneID == 1 && checkEMR == 0) || (checkPhoneR == 0 && checkEMR == 0)){
          jLabel14.setVisible(false);
         jLabel15.setVisible(false);
         saveonlyabove();
         }
         else if((checkPhoneR == 1 && checkEMR == 1 && EmailID == 0 && PhoneID == 0 )){
         JOptionPane.showMessageDialog(null, "Email and Phone Number has already been use");
        jLabel14.setVisible(true);
         jLabel15.setVisible(true);
           jLabel14.setForeground(Color.red);
             jLabel15.setForeground(Color.red);
         jLabel14.setText("This Email has already been use");
         jLabel15.setText("This Phone Number has already been use");
         }
          else if(checkPhoneR == 1){
         JOptionPane.showMessageDialog(null, "Phone Number has already been use");
            jLabel14.setVisible(false);
         jLabel15.setVisible(true);
         jLabel15.setForeground(Color.red);
          jLabel15.setText("This Phone has already been use");
         }
          else if(checkEMR == 1){
             jLabel15.setVisible(false);   
         JOptionPane.showMessageDialog(null, "Email has already been use");
          jLabel14.setVisible(true);
          jLabel14.setForeground(Color.red);
          jLabel14.setText("This Email Number has already been use");
         }
         
        }
        
        }
        catch(Exception e){
JOptionPane.showMessageDialog(null, "not connected");
}
        
        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void saveonlyabove(){
      String FN =FNshow.getText();
        String LN = LNshow.getText();
        String EM = EMshow.getText();
        String PN = PNshow.getText();
        
        try{     
            Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
        
      String sql = " UPDATE admin_account SET Admin_FName= ? , Admin_LName = ?  , Admin_Email = ?, Admin_PhoneNum = ? WHERE Admin_ID= ?;";
        PreparedStatement st = con.prepareStatement(sql); 
       
        st.setString(1, FN);
        st.setString(2, LN);
        st.setString(3, EM);
        st.setString(4, PN);
        st.setInt(5, IDuser);
        
   int h = st.executeUpdate();

    if(h>0){ JOptionPane.showMessageDialog(null, "Updated");
       EmailfromID = EM;
       PhonefromID = PN;
}
    
    }
             catch(Exception e){
JOptionPane.showMessageDialog(null, "not connected");
}
    }
    
    
    private void EMshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMshowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMshowActionPerformed
int  a = 0;
    private void GetPSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GetPSKeyReleased
          PSChecker.setVisible(true);
           checkforpasswordsim();
        String Password = GetPS.getText();
        int length = Password.length();

        String sample = GetPS.getText();
        char[] chars = sample.toCharArray();
        StringBuilder sb = new StringBuilder();
        StringBuilder sbs = new StringBuilder();
        for(char c : chars){
            if(Character.isDigit(c)){
                sb.append(c);
                sbs.append(c);
            }
        }

        String singleString = sb.toString();
        if (singleString.isEmpty()){
            if(length >= 0 && length <= 5){
                PSChecker.setForeground(Color.red);
                PSChecker.setText("Weak");
                a = 1;
            }
            else if(length >= 6 ){
                PSChecker.setForeground(Color.ORANGE);
                PSChecker.setText("Ok");
                a = 2;
            }

        }
        else{
            if(length >= 0 && length <= 5){
                PSChecker.setForeground(Color.red);
                PSChecker.setText("Weak");
                a = 1;
            }
            else if(length >= 6 ){
                PSChecker.setForeground(Color.GREEN);
                PSChecker.setText("Strong");
                a = 3;
            }
        }
    }//GEN-LAST:event_GetPSKeyReleased

    private void GetRPPSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GetRPPSKeyReleased
        checkforpasswordsim();
    }//GEN-LAST:event_GetRPPSKeyReleased

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
    String oldpass = OldPSshow.getText();
      String newpass = GetPS.getText(); 
      String renewpass = GetRPPS.getText(); 
       
      if(oldpass.equals("") || newpass.equals("") || renewpass.equals("")){
      
          JOptionPane.showMessageDialog(null, "Please fill all boxese");
          
      if(oldpass.equals("")){
       jLabel16.setVisible(true);
       jLabel16.setForeground(Color.red);
       jLabel16.setText("Current password not fill");
       }
       else{
         jLabel16.setVisible(false);
       }
      
      if(newpass.equals("")){
       PSChecker.setVisible(true);
       PSChecker.setForeground(Color.red);
       PSChecker.setText("New password not fill");
       }
       else{
         PSChecker.setVisible(false);
       }
      
        if(renewpass.equals("")){
       RPPSChecker.setVisible(true);
       RPPSChecker.setForeground(Color.red);
       RPPSChecker.setText("New repeated password not fill");
       }
       else{
         RPPSChecker.setVisible(false);
       }
      
      
      }
      else{
      if(getpassword.equals(oldpass)){
            
                 if ( a == 1 ){
            JOptionPane.showMessageDialog(this, "Please make your password longer and add number some number into your password as while");
        }
                 else if(a ==2){
                     JOptionPane.showMessageDialog(this, "Please add some number into your password");
                 }
                 else if(a == 3){
                 savepassinfo();
                 }
                 else{
                  JOptionPane.showMessageDialog(this, "Something is wrong with your password and repeat password, please rewrite password and repeat password again");
                 }
        
     }   
        else{
        JOptionPane.showMessageDialog(null, "Current password is incorrect");
        jLabel16.setForeground(Color.red);
        jLabel16.setText("Incorrect");
        }
      }
    }//GEN-LAST:event_jToggleButton2ActionPerformed
private void savepassinfo(){
String Newpass = GetPS.getText();
    try{     
            Class.forName("com.mysql.jdbc.Driver");
    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","Ilikeminecraft040610");
   Statement myStat = con.createStatement();
        
      String sql = " UPDATE admin_account SET Admin_password = ?  WHERE Admin_ID= ?;";
        PreparedStatement st = con.prepareStatement(sql); 
       st.setString(1, Newpass);
       st.setInt(2, IDuser);
   
        
   int h = st.executeUpdate();

    if(h>0){ JOptionPane.showMessageDialog(null, "Updated Password");
    getpassword = Newpass;
    jLabel16.setVisible(false);
}
    
    }
             catch(Exception e){
JOptionPane.showMessageDialog(null, "not connected");
}
    
}
    
    private void checkforpasswordsim(){
          RPPSChecker.setVisible(true);
        String Password, RePassword;
        Password = GetPS.getText();
        RePassword = GetRPPS.getText();
        if(0==Password.compareTo(RePassword)){
            RPPSChecker.setForeground(Color.green);
            RPPSChecker.setText("Correct");
        }
        else{RPPSChecker.setForeground(Color.red);
            RPPSChecker.setText("Incorrect");}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_AccountSetting_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_AccountSetting_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_AccountSetting_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_AccountSetting_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_AccountSetting_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EMshow;
    private javax.swing.JTextField FNshow;
    private javax.swing.JPasswordField GetPS;
    private javax.swing.JPasswordField GetRPPS;
    private javax.swing.JTextField LNshow;
    private javax.swing.JLabel Logout;
    private javax.swing.JPasswordField OldPSshow;
    private javax.swing.JTextField PNshow;
    private javax.swing.JLabel PSChecker;
    private javax.swing.JLabel RPPSChecker;
    private javax.swing.JLabel Setting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel showName;
    // End of variables declaration//GEN-END:variables
}
